Add network name (Display Network Name as in Old Website)
jediswaplabs/JediSwapE2-interface pull request #63
Opened 2023-11-08 16:26 UTC by pizzooid

Closes #51  

![Screenshot 2023-11-08 170542](https://github.com/jediswaplabs/JediSwapE2-interface/assets/3073099/9fa4d730-55ba-48b7-90d8-bcb1f03bb22b)

I used styled components. Is that correct?

Check out [src/components/NavBar/NetworkName.tsx:41](https://github.com/jediswaplabs/JediSwapE2-interface/compare/retroboy/swap-ui...add-network-name?expand=1#diff-96d881a7e10c9fb47b13fc5f2d9ff016053a6b8ece9cd64be92af48ff30bbeaeR41) if this is the correct behavior:
It hides the box if chainId or account is not shown. (compare [Figma](https://www.figma.com/file/UnuRGVIl2GLHyLSDGxajwp/JediSwap---Webapp-v2?node-id=1716%3A13338&mode=dev))

2023-11-08 17:30 UTC, retroboydev requested changes

2023-11-08 17:30 UTC, retroboydev commented on src/components/NavBar/NetworkName.tsx
> +  background: var(--Jedi-Navy-Blue, #141451);
please extract this color from the theme like that:
```background: ${({ theme }) => theme.jediNavyBlue};```

2023-11-08 17:30 UTC, retroboydev commented on src/components/NavBar/NetworkName.tsx
> +  color: var(--Jedi-White, #FFF);
same as above

2023-11-08 17:30 UTC, retroboydev commented on src/components/NavBar/styled.tsx
> +  display: none;
we need to solve this problem somehow since we should always display the connected network plate. I would suggest to update the logic of hiding-and-moving-below the top menu, and switch it to the previous breakpoint (earlier) instead of the current one. 
also, let's reduce the space between the connected wallet plate and the network name plate, it seems to big now. 
feel free to play around it a bit and try to solve this issue. if it doesn't work, please ping me in discord and I will connect you with our designer.

2023-11-08 17:31 UTC, retroboydev commented
otherwise it looks cool :-)

2023-11-11 15:04 UTC, pizzooid commented
Thank you for the review!

Here are the updated views:
![Screenshot 2023-11-11 155715](https://github.com/jediswaplabs/JediSwapE2-interface/assets/3073099/cefca6c0-1e0a-4693-9756-4c88a50744a4)
![Screenshot 2023-11-11 155727](https://github.com/jediswaplabs/JediSwapE2-interface/assets/3073099/8192fe53-5b21-4c61-86c6-47db1b6e4919)
![Screenshot 2023-11-11 155752](https://github.com/jediswaplabs/JediSwapE2-interface/assets/3073099/5d08e973-68e0-4293-be2a-98d8a7f5e67c)
![Screenshot 2023-11-11 155804](https://github.com/jediswaplabs/JediSwapE2-interface/assets/3073099/3b01e7f9-19ac-40d1-8703-8fa3cbb63892)

As you can see in the third screenshot, the menu moves a bit to the right, how do you think this should be done?

2023-11-12 17:23 UTC, retroboydev commented
@pizzooid let's keep it this way now, we will fix it later. thank you!

2023-11-12 17:23 UTC, merged

2023-11-12 17:24 UTC, retroboydev reviewed
good